# -*- coding: utf-8 -*-
"""Data visualization mini project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ix5W_-UgPFTi-bz1Xkq14DqgsVwNA05
"""

import openpyxl
import pandas as pd

workbook = openpyxl.Workbook()
sheet = workbook.active

data=[
    ["NAME","DOMAIN","AGE","LOCATION","SALARY","EXP"],
    ["ALEX","TESTING",25,"BNG",5000,2],
    ["BARD","JAVA",30,"CHE",10000,3],
    ["CHERRY","C",35,"PUNE",15000,4],
    ["DIPAN","DA",38,"MUMBAI",20000,5],
    ["ESWAR","DS",40,"HYD",50000,6]
]
for row in data:
  sheet.append(row)
workbook.save("data.xlsx")

data

df=pd.read_excel("data.xlsx")
print(df)

import os
os.getcwd()

emp=pd.read_excel("data.xlsx")
emp

emp.shape

emp.columns

len(emp.columns)

len(emp)

emp[["SALARY","EXP","AGE"]]

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

vis1=sns.displot(emp["SALARY"])

vis2=sns.distplot(emp["SALARY"])

vis3=plt.hist(emp["SALARY"])

plt.rcParams['figure.figsize'] = 5,1

# vis5=sns.lmplot(data=emp, x="EXP",y="SALARY")
# vis5=sns.lmplot(data=emp, x="EXP",y="SALARY",fit_reg=False)# line will not come
vis5=sns.lmplot(data=emp, x="EXP",y="SALARY",fit_reg=True)#line will come





